#include <assert.h>
#include <limits.h>
#include <math.h>
#include <stdint.h>
#include <string.h>

#if defined __cplusplus
#include <fstream>
#include <iostream>
#include <algorithm>
#include <iterator>
#include <QAbstractTableModel>
#include <QAction>
#include <QApplication>
#include <QBitmap>
#include <QBrush>
#include <QClipboard>
#include <QColorDialog>
#include <QCursor>
#include <QDateTime>
#include <QDialog>
#include <QDir>
#include <QDomDocument>
#include <QDomElement>
#include <QDomNode>
#include <QDragEnterEvent>
#include <QDropEvent>
#include <QEvent>
#include <QFile>
#include <QFileDialog>
#include <QHBoxLayout>
#include <QImage>
#include <QImageReader>
#include <QItemDelegate>
#include <QLabel>
#include <QList>
#include <QListIterator>
#include <QListWidget>
#include <QLocale>
#include <QMainWindow>
#include <QMenu>
#include <QMenuBar>
#include <QMessageBox>
#include <QMimeData>
#include <QModelIndex>
#include <QObject>
#include <QObjectList>
#include <QPainter>
#include <QPainterPath>
#include <QPaintEvent>
#include <QPen>
#include <QPixmap>
#include <QProgressBar>
#include <QProgressDialog>
#include <QPushButton>
#include <QRect>
#include <QRgb>
#include <QScrollArea>
#include <QScrollBar>
#include <QStatusBar>
#include <QString>
#include <QStringList>
#include <QTextCodec>
#include <QTextStream>
#include <QThread>
#include <QTranslator>
#include <QUrl>
#include <QValidator>
#include <QVariant>
#include <QVBoxLayout>
#include <QWidget>
#include <stdexcept>
#include <string>
#include <vector>
#endif
